/**
 * @file tcs34725_interrupt_test.c
 * @brief TCS34725 color sensor interrupt mode test implementation
 *
 * Hardware connections:
 *   TCS34725 VCC  -> STM32 3.3V
 *   TCS34725 GND  -> STM32 GND
 *   TCS34725 SDA  -> STM32 PB7  (I2C1_SDA, AF4)
 *   TCS34725 SCL  -> STM32 PB6  (I2C1_SCL, AF4)
 *   TCS34725 INT  -> STM32 PA0  (GPIO EXTI0, falling edge, pull-up)
 *   TCS34725 LED  -> 3.3V through 10 ohm resistor (or leave open)
 *
 * UART output: USART2 at 115200 baud
 *   PA2 -> USART2_TX  (connect to USB-UART RXD)
 *   PA3 -> USART2_RX  (connect to USB-UART TXD)
 *   GND -> USB-UART GND
 */

#include "tcs34725_interrupt_test.h"
#include <stdio.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/* Globals                                                              */
/* ------------------------------------------------------------------ */

extern volatile uint8_t g_interrupt_flag;

/* UART handle generated by CubeMX in main.c */
extern UART_HandleTypeDef huart2;

/* ------------------------------------------------------------------ */
/* Static helpers                                                       */
/* ------------------------------------------------------------------ */

static void uart_print(const char *str)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)str, (uint16_t)strlen(str), 1000U);
}

static void print_rgbc(uint32_t count, uint16_t r, uint16_t g, uint16_t b, uint16_t c)
{
    char buf[80];
    snprintf(buf, sizeof(buf),
             "[%02lu] R=%5u  G=%5u  B=%5u  C=%5u\r\n",
             (unsigned long)count, r, g, b, c);
    uart_print(buf);
}

/* ------------------------------------------------------------------ */
/* EXTI callback                                                        */
/* ------------------------------------------------------------------ */

/* 
 * Remove duplicate HAL_GPIO_EXTI_Callback definition to avoid multiple definition error.
 * Move the GPIO_PIN_0 handling code to your existing HAL_GPIO_EXTI_Callback implementation.
 */

/* ------------------------------------------------------------------ */
/* Test functions                                                       */
/* ------------------------------------------------------------------ */

